### ISSUE TITLE
where is the zip？

### ISSUE THREAD

**Issue by tl-lee** [04637/showProxyTarget#1]
i can‘t find the zip to download

**Comment by jiguantong** [comment]
> i can‘t find the zip to download


这里, [showProxyTarget.zip](https://github.com/04637/showProxyTarget/files/7773300/showProxyTarget.zip)
这是我给我们公司的一个低代码平台做的, 不一定通用
如果你需要用, 遇到问题可以联系我可以适配你的环境, 我们可以进一步沟通
